import React, { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
import sdk, { Project } from '@stackblitz/sdk';
import { useProjectStore } from '@/stores/projectStore';
import { getStackBlitzFiles } from '@/utils/stackBlitzUtils';
import { Loader2 } from 'lucide-react';
import { useAIStore } from '@/stores/aiStore';
import { usePreviewStore } from '@/stores/previewStore';

interface StackBlitzPreviewProps {
  className?: string;
}

export type StackBlitzPreviewHandle = {
  resetVM: () => void;
};

export const StackBlitzPreview = forwardRef<StackBlitzPreviewHandle, StackBlitzPreviewProps>(({ className }, ref) => {
  const { files, stack } = useProjectStore();
  const embedRef = useRef<HTMLDivElement>(null);
  const [isLoading, setIsLoading] = useState(true);
  const vmRef = useRef<any>(null);
  const prevFilesRef = useRef<Record<string, string>>({});
  const { appendSystemConsoleContent, appendThinkingContent } = useAIStore();
  const { setRuntimeStatus, setPreviewUrl } = usePreviewStore();
  const STABLE_KEY = 'apex-stable-files';

  function resetVMInternal() {
    try {
      const raw = localStorage.getItem(STABLE_KEY);
      const stable = raw ? JSON.parse(raw) : null;
      const current = getStackBlitzFiles(files);
      const fallback = stable && typeof stable === 'object' ? stable : current;
      const create = fallback;
      const destroy = Object.keys(prevFilesRef.current).filter((k) => !(k in fallback));
      vmRef.current?.applyFsDiff({ create, destroy });
      prevFilesRef.current = fallback;
      setRuntimeStatus('starting');
      appendSystemConsoleContent(`${new Date().toLocaleTimeString([], { hour12: false })} [STATUS] VM reset. Re-starting preview…\n`);
    } catch {
      appendSystemConsoleContent(`${new Date().toLocaleTimeString([], { hour12: false })} [WARNING] Reset failed. Using current workspace.\n`);
    }
  }

  useEffect(() => {
    let isMounted = true;

    const embedProject = async () => {
      if (typeof window === 'undefined') return;
      if (!embedRef.current) return;

      const sbFiles = getStackBlitzFiles(files);
      setRuntimeStatus('booting');
      appendSystemConsoleContent(`${new Date().toLocaleTimeString([], { hour12: false })} [STATUS] Booting WebContainer…\n`);
      
      const project: Project = {
        title: 'Apex Coding Project',
        description: 'Generated by Apex Coding',
        template: 'node',
        files: sbFiles,
        settings: {
          compile: {
            trigger: 'auto',
            clearConsole: false,
          },
        },
      };

      try {
        // Check if embedRef is valid
        if (!embedRef.current) {
             console.warn('Embed container not ready');
             setRuntimeStatus('error', 'embed container not ready');
             return;
        }

        // Embed the project
        const vm = await sdk.embedProject(embedRef.current, project, {
          openFile: 'src/App.tsx,src/main.tsx,index.html',
          view: 'preview',
          height: '100%',
          width: '100%',
          hideExplorer: true,
          hideNavigation: false,
          forceEmbedLayout: true,
        });

        if (isMounted) {
            vmRef.current = vm;
            setIsLoading(false);
            prevFilesRef.current = sbFiles;
            setRuntimeStatus('starting');
            appendSystemConsoleContent(`${new Date().toLocaleTimeString([], { hour12: false })} [STATUS] Starting dev server…\n`);
            try {
              await vm.editor.setView('preview');
            } catch {}
            try {
              const snapshot = await vm.getFsSnapshot();
              if (snapshot) {
                localStorage.setItem(STABLE_KEY, JSON.stringify(snapshot));
              }
            } catch {}
            try {
              const origin = vm.preview?.origin || '';
              if (origin) setPreviewUrl(origin);
            } catch {}
            const iframe = embedRef.current.querySelector('iframe');
            if (iframe) {
              iframe.addEventListener('error', () => {
                setRuntimeStatus('error', 'preview iframe error');
                appendSystemConsoleContent(`${new Date().toLocaleTimeString([], { hour12: false })} [ERROR] Preview failed to render.\n`);
                appendThinkingContent('[THOUGHT] Detected preview error. Resetting to stable build…\n');
                resetVMInternal();
              });
              iframe.addEventListener('load', () => {
                setRuntimeStatus('ready');
                appendSystemConsoleContent(`${new Date().toLocaleTimeString([], { hour12: false })} [STATUS] Preview ready.\n`);
              });
            }
        }
      } catch (error) {
        console.error('Failed to embed StackBlitz project:', error);
        setRuntimeStatus('error', 'embed failed');
        appendSystemConsoleContent(`${new Date().toLocaleTimeString([], { hour12: false })} [ERROR] Failed to embed project.\n`);
        appendThinkingContent('[THOUGHT] Detected embed failure. Resetting to stable build…\n');
        resetVMInternal();
        if (isMounted) setIsLoading(false);
      }
    };

    // Small delay to ensure DOM is ready
    const initTimer = setTimeout(embedProject, 100);

    return () => {
      isMounted = false;
      clearTimeout(initTimer);
    };
  }, []); // Initial load

  // Sync logic - debounce updates
  useEffect(() => {
    if (!vmRef.current) return;

    const timer = setTimeout(() => {
        const nextFiles = getStackBlitzFiles(files);
        const create: Record<string, string> = {};
        const destroy: string[] = [];
        const prev = prevFilesRef.current;
        for (const key of Object.keys(nextFiles)) {
          if (!(key in prev) || prev[key] !== nextFiles[key]) {
            create[key] = nextFiles[key];
          }
        }
        for (const key of Object.keys(prev)) {
          if (!(key in nextFiles)) {
            destroy.push(key);
          }
        }
        if (Object.keys(create).length > 0 || destroy.length > 0) {
          appendSystemConsoleContent(`${new Date().toLocaleTimeString([], { hour12: false })} [STATUS] Applying ${Object.keys(create).length} change(s), removing ${destroy.length} file(s)…\n`);
          vmRef.current.applyFsDiff({ create, destroy });
          prevFilesRef.current = nextFiles;
          try {
            localStorage.setItem(STABLE_KEY, JSON.stringify(nextFiles));
          } catch {}
        }
    }, 400); // Reduced to 400ms for snappier updates

    return () => clearTimeout(timer);
  }, [files]);

  useImperativeHandle(ref, () => ({
    resetVM: () => resetVMInternal()
  }));

  return (
    <div className={`relative w-full h-full ${className}`}>
      {isLoading && (
        <div className="absolute inset-0 flex items-center justify-center bg-gray-900 z-10">
          <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
          <span className="ml-2 text-white">Initializing Environment...</span>
        </div>
      )}
      <div ref={embedRef} className="w-full h-full" />
    </div>
  );
});

StackBlitzPreview.displayName = 'StackBlitzPreview';
