import React, { useEffect, useRef, useState } from 'react';
import sdk, { Project } from '@stackblitz/sdk';
import { useProjectStore } from '@/stores/projectStore';
import { getStackBlitzFiles } from '@/utils/stackBlitzUtils';
import { Loader2 } from 'lucide-react';

interface StackBlitzPreviewProps {
  className?: string;
}

export const StackBlitzPreview: React.FC<StackBlitzPreviewProps> = ({ className }) => {
  const { files, stack } = useProjectStore();
  const embedRef = useRef<HTMLDivElement>(null);
  const [isLoading, setIsLoading] = useState(true);
  const vmRef = useRef<any>(null);

  useEffect(() => {
    let isMounted = true;

    const embedProject = async () => {
      if (typeof window === 'undefined') return;
      if (!embedRef.current) return;

      const sbFiles = getStackBlitzFiles(files);
      
      const project: Project = {
        title: 'Apex Coding Project',
        description: 'Generated by Apex Coding',
        template: 'node', // Using node template for maximum flexibility with Vite
        files: sbFiles,
        settings: {
          compile: {
            trigger: 'auto',
            clearConsole: false,
          },
        },
      };

      try {
        // Check if embedRef is valid
        if (!embedRef.current) {
             console.warn('Embed container not ready');
             return;
        }

        // Embed the project
        // We use 'node' template but with Vite setup, it essentially behaves like vite-react-ts but more robust via WebContainers
        const vm = await sdk.embedProject(embedRef.current, project, {
          openFile: 'src/App.tsx,src/main.tsx,index.html',
          view: 'preview',
          height: '100%',
          width: '100%',
          hideExplorer: true,
          hideNavigation: false,
          forceEmbedLayout: true,
        });

        if (isMounted) {
            vmRef.current = vm;
            setIsLoading(false);
        }
      } catch (error) {
        console.error('Failed to embed StackBlitz project:', error);
        if (isMounted) setIsLoading(false);
      }
    };

    // Small delay to ensure DOM is ready
    const initTimer = setTimeout(embedProject, 100);

    return () => {
      isMounted = false;
      clearTimeout(initTimer);
    };
  }, []); // Initial load

  // Sync logic - debounce updates
  useEffect(() => {
    if (!vmRef.current) return;

    const timer = setTimeout(() => {
        const sbFiles = getStackBlitzFiles(files);
        // We apply fs diff
        vmRef.current.applyFsDiff({
            create: sbFiles,
            destroy: [] 
        });
    }, 400); // Reduced to 400ms for snappier updates

    return () => clearTimeout(timer);
  }, [files]);

  return (
    <div className={`relative w-full h-full ${className}`}>
      {isLoading && (
        <div className="absolute inset-0 flex items-center justify-center bg-gray-900 z-10">
          <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
          <span className="ml-2 text-white">Initializing Environment...</span>
        </div>
      )}
      <div ref={embedRef} className="w-full h-full" />
    </div>
  );
};
