import JSZip from 'jszip';
import { ProjectFile } from '../../../shared/types.js';

const DEFAULT_ROOT_PACKAGE_JSON = JSON.stringify(
  {
    name: 'project-root',
    scripts: {
      start: 'concurrently "npm run server" "npm run client"',
      server: 'cd backend && node server.js',
      client: 'cd frontend && vite'
    },
    dependencies: {
      concurrently: '^8.0.0',
      express: '^4.18.0',
      sqlite3: '^5.1.0',
      cors: '^2.8.5',
      nodemon: '^3.0.0'
    }
  },
  null,
  2
) + '\n';

const normalizePath = (raw: string) =>
  (raw || '')
    .replace(/\\/g, '/')
    .replace(/^(\.\/)+/, '')
    .replace(/^\/+/, '')
    .trim();

export class ZipGenerator {
  async generateZip(
    files: ProjectFile[],
    projectName: string,
    description: string,
    stack: string
  ): Promise<Buffer> {
    const zip = new JSZip();

    const fileMap = new Map<string, string>();

    // Add all project files (prefer `path`, fallback to `name`)
    for (const file of files) {
      const path = normalizePath(file.path || file.name || '');
      if (!path) continue;
      fileMap.set(path, file.content || '');
    }

    // Ensure a root package.json for local execution.
    if (!fileMap.has('package.json')) {
      fileMap.set('package.json', DEFAULT_ROOT_PACKAGE_JSON);
    }

    for (const [path, contents] of fileMap.entries()) {
      zip.file(path, contents);
    }

    // Generate README
    const readme = this.generateReadme(projectName, description, stack);
    zip.file('README.md', readme);

    // Generate ZIP
    const buffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 9 }
    });

    return buffer;
  }

  private generateReadme(projectName: string, description: string, stack: string): string {
    return `# ${projectName}

${description}

## Technology Stack

${stack}

## Setup Instructions

### Prerequisites

Ensure you have the following installed:
${this.getPrerequisites(stack)}

### Installation

1. Extract the ZIP file
2. Navigate to the project directory
3. Install dependencies:
${this.getInstallCommands(stack)}

### Running the Project

${this.getRunCommands(stack)}

## Project Structure

This project was generated by NEXUS AI CODING.

## License

MIT

---

Generated with NEXUS AI CODING - 100% Offline AI-Powered Development Platform
`;
  }

  private getPrerequisites(stack: string): string {
    if (stack.includes('React') || stack.includes('Node')) {
      return '- Node.js (v18 or higher)\n- npm or yarn';
    } else if (stack.includes('Python')) {
      return '- Python 3.8 or higher\n- pip';
    }
    return '- A modern web browser';
  }

  private getInstallCommands(stack: string): string {
    if (stack.includes('React') || stack.includes('Node')) {
      return '```bash\n# from the project root\nnpm install\n```';
    } else if (stack.includes('Python')) {
      return '```bash\npip install -r requirements.txt\n```';
    }
    return 'No installation required - open index.html in a browser';
  }

  private getRunCommands(stack: string): string {
    if (stack.includes('React')) {
      return '```bash\n# from the project root\nnpm start\n```\n\nThe client will be available at http://localhost:5173 and the API at http://localhost:3111';
    } else if (stack.includes('Node')) {
      return '```bash\n# from the project root\nnpm start\n```\n\nThe server will start on the configured port (default: 3111)';
    } else if (stack.includes('Flask')) {
      return '```bash\npython app.py\n```\n\nThe server will start on http://localhost:5000';
    } else if (stack.includes('FastAPI')) {
      return '```bash\nuvicorn main:app --reload\n```\n\nThe API will be available at http://localhost:8000';
    }
    return 'Open index.html in your web browser';
  }
}

export const zipGenerator = new ZipGenerator();
