import express from 'express';
import { zipGenerator } from '../services/zipGenerator.js';
import { logger } from '../utils/logger.js';

const router = express.Router();

router.post('/zip', async (req, res) => {
  try {
    const { files, projectName, description, stack } = req.body;

    if (!files || !Array.isArray(files)) {
      return res.status(400).json({ error: 'Files array is required' });
    }

    logger.info(`Generating ZIP for project: ${projectName}`);

    const zipBuffer = await zipGenerator.generateZip(
      files,
      projectName || 'nexus-project',
      description || 'Generated by NEXUS AI CODING',
      stack || 'Unknown'
    );

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${projectName || 'project'}.zip"`);
    res.send(zipBuffer);
  } catch (error: any) {
    logger.error('ZIP generation error', {
      message: error?.message,
      status: error?.response?.status,
      data: error?.response?.data,
      code: error?.code
    });
    res.status(500).json({ error: error.message || 'Failed to generate ZIP' });
  }
});

export default router;
