
/**
 * Helper to embed a StackBlitz project in a website.
 * Usage: openProjectInStackBlitz('my-element-id', projectData);
 */
import sdk from '@stackblitz/sdk';

interface ProjectFiles {
  [path: string]: string;
}

export function openProjectInStackBlitz(elementId: string, files: ProjectFiles, title: string = 'Generated Project') {
  sdk.embedProject(
    elementId,
    {
      title: title,
      description: 'A project generated by Apex Coding',
      template: 'node',
      files: files,
      settings: {
        compile: {
          trigger: 'auto',
          clearConsole: false,
        },
      },
    },
    {
      openFile: 'frontend/src/App.tsx,frontend/index.html',
      view: 'preview',
      height: '100%',
    }
  );
}

export function openGithubProject(repoSlug: string, elementId: string) {
  sdk.embedGithubProject(elementId, repoSlug, {
    openFile: 'frontend/src/App.tsx,frontend/index.html',
    view: 'preview',
    height: '100%',
  });
}
